export const ADD = "ADD"
export const SUB = "SUB"
export const GET_MOVIES = "GET_MOVIES"

export const LOADING = "LOADING"

export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const REGISTER = "REGISTER"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const LOGOUT = "LOGOUT"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"

export const GET_LIST_PRODUCT = "GET_LIST_PRODUCT"
export const GET_LIST_PRODUCT_SUCCESS = "GET_LIST_PRODUCT_SUCCESS"
export const GET_LIST_PRODUCT_FAIL = "GET_LIST_PRODUCT_FAIL"

export const GET_FAVORITE_QUOTES = "GET_FAVORITE_QUOTES"
export const GET_FAVORITE_QUOTES_SUCCESS = "GET_FAVORITE_QUOTES_SUCCESS"
export const GET_FAVORITE_QUOTES_FAIL = "GET_FAVORITE_QUOTES_FAIL"

export const GET_QUOTE_DETAIL = "GET_QUOTE_DETAIL"
export const GET_QUOTE_DETAIL_SUCCESS = "GET_QUOTE_DETAIL_SUCCESS"
export const GET_QUOTE_DETAIL_FAIL = "GET_QUOTE_DETAIL_FAIL"

export const CREATE_QUOTE = "CREATE_QUOTE"
export const CREATE_QUOTE_SUCCESS = "CREATE_QUOTE_SUCCESS"
export const CREATE_QUOTE_FAIL = "CREATE_QUOTE_FAIL"


