$FirebaseSDKVersion = '6.29.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'rnkit' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'  


  target 'rnkitTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #  
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
